### ISSUE TITLE
Better Incremental Filer API

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/incap#70]
Not sure about this one. But we could have something like:
```java
createClassFile(CharSequence name, Element firstEntryElement, Element... otherEntryElements)
```

to force having at least one. A small trick I learnt recently in compile-testing.

**Comment by stephanenicolas** [comment]
Let's describe the issues related to this:

* we want to pass a list of entry point type elements for incap
* and also originating elements for the originating filer (other tools might need this info, IDEs for instance)
* we want to be able to pass a single entry point in M1, and multiple elements in M2, ideally our API will have to offer a backward compatibility
* it's not possible to use more than 1 var args per method signature.

(Add more stuff here to describe the tensions we face in designing the API, if needed).

**Comment by stephanenicolas** [comment]
We could create a builder:
```java
forSourceFile(String fqn)
  .usingEntryPoints(TypeElement...)
  .fromOriginatingElements(Element...)
  .create();
```

Or, in a more accumulative way:
```java
forSourceFile(String fqn)
  .addEntryPoint(TypeElement)
  .addOriginatingElements(Element)
  .create();
```

**Comment by oehme** [comment]
There is no difference between "entry point" and "originating element". The JavaDoc says `The elements **causally** related to the **creation** of this file`. On other words, if all these originating elements are removed, the generated file will no longer be there. There might be many other "related elements" that affect the **content** of the file. They can come and go, but the file will still be **created** as long as the originating element is there. That's the same as what we mean by "entry point" - if the entry point is gone, the generated file is gone. The transitive closure of that entry point only affects the content of the file, not whether it is created.

Also, since we want to be compatible with the existing `Filer` API, we can't "force" at least one element, because we'll need to provide the original methods anyway.
