### ISSUE TITLE
Set up publishing to Gradle repository

### ISSUE THREAD

**Issue by oehme** [gradle/incap#88]
For our initial experiments, we want to publish Incap to Gradle's repository, so we no longer need to use Jitpack. Later on we'll want to publish to Jcenter/Maven Central as well.

**Comment by jjohannes** [comment]
I added the publishing job here:
https://builds.gradle.org/viewType.html?buildTypeId=Incap_Publish

For starters I set the version to `0.1.0-SNAPSHOT`.

You can now get it from the Gradle repo:
```
repositories {
    maven { url 'https://repo.gradle.org/gradle/libs-snapshots' }
}

dependencies {
    compile 'org.gradle.incap:incap-model:0.1.0-SNAPSHOT'
}
```

**Comment by jjohannes** [comment]
How often do we want the job to run? On every `master` change or nightly (also only if there is a change)?

**Comment by stephanenicolas** [comment]
Hi jendrik, I am not used to continuous deployment. Can we have a CI check job on every PR + master merge and a deploy on demand ?
Can we release snapshots only, where do you set the version number ?

**Comment by oehme** [comment]
Let's publish the snapshot on every change to master and do a release on demand (done by the Gradle team).

**Comment by stephanenicolas** [comment]
@oehme If we could release things below 1.0.0 it would be nice. 
It would make things more easy for us to control snapshots and releases for versions 0.y.z.
We are building around 4-5 projects around incap and we also need to release stable artifact from times to time to syncrhonize all things.

**Comment by oehme** [comment]
Please just shoot us a message when you need a stable release. We want to keep full control over what is available on our releases repository.

**Comment by stephanenicolas** [comment]
it's not very convenient for sure, even less with 9 hours of time difference.. But let's try. What we can do is to tag a stable commit with a non snapshot version number, as if we had released it, then bump our snapshot version number. We will pass you the tag to release this very specific commit.

**Comment by oehme** [comment]
I'm not sure I see the problem yet - you'll have an up-to-date snapshot as soon as you commit. A stable release is only needed once we want to start rolling this out for real.

**Comment by stephanenicolas** [comment]
Not only, the thing is that we have to synchronize our other libs to test everything and snapshots can be easily erased. It's gonna be working without having any stability at all. You finish your work one day, butter knife and auto value and the new york app work fine. You come back 2 days after and all is broken because they all depended on a snapshot that changed.
And that's even more true as Steve, Weihua and me work on different part of the system, all depending on incap. It's gonna be hard without a careful release cycle to develop simultaneously.

**Comment by oehme** [comment]
You can always bump the base version number of the snapshot. E.g. go from 0.0.1-SNAPSHOT to 0.0.2-SNAPSHOT.

**Comment by jjohannes** [comment]
I set the CI job to publish a snapshot on every master commit, IF the Linux check was successful. I would also add the Windows check as dependency, but that is still broken at the moment.

**Comment by stephanenicolas** [comment]
Yes, sure. I was suggesting above that:
* we follow a standard release procedure: prepare commit before release, with a non snapshot version, tag it. But we don't release.
* then we bump to the next snapshot version and commit and push. Like a real release procedure.
* we will give you the tag so that you can release it. 

It's not going to be very convenient for us and it will not follow the pace of the development on our side, but hopefully we can manage it.

**Comment by stephanenicolas** [comment]
Finally, I've found a compromise that will be acceptable for everyone:
* we are gonna use CI to deploy snapshots on gradle repo. 
* we are gonna use bintray to release 0.y.z shared artifacts. 

I created a repo on bintray for an organization named incap. If you wanna have access to them, ping me on slack to give me your bintray user name. (This is needed only to release artifacts on bintray).
